os: linux
dist: bionic
language: generic
addons:
  apt:
    packages:
      - libgmp-dev
env:
  global:
    - HACKAGE_USERNAME=fozworth
    # HACKAGE_PASSWORD
    - secure: "vxrduhHNLKRRkUjzmr0hMlVfhgGQYx4YQwwic6eBlhy3EFUFJueRU0kaNU9r/1lNMrrxr02WDqE8u+1ce21zpQUGb/JC1UarpoYr74RwqPqpHEr6GjM5Lh3I4LOrj8EbXf40UtwxW1Iyu33UlTdC+1592PTjVPxYvvUk53GrQaOUFBRlHnxokLQ2fRKJorbIPjmAmIE8n12I6JGKOKy1lfXE3JueCnJBwBI2I0To8VpRwJ2k+kyd/Et9s5x3GFoVnyEgKDZZ3qSwHa3CMXYZJTJoxeueT04JdqCl6XkNojrjter3Aq5wvTA1ZYQhihrF2NtYTW74++1PP0JqPeeBtMqqvWi/MUAwp6VbrZC2+tt+MLd2mcYVkAh+0vKxLOUwsrOr4maC8OiauLOwMgr+HuYAhLdlBZO6lX21werPqWqnQ9/U9fA++BUbaQW3N4VwVPYDZ9gLObEkuAjSN9lP5yikcGCIXbs2cSHeip+M0nioUF44h1eA85c5gEriJebIMWwBHp+stgPK6p8jic00rQxBJ3fFQe19wsIHD37m3rtiBHSXyRPoBb3HPav6or4w3HQZpF2rbfOYHS9JrTZN7okBiFjiRlFk4vucrVRvFtTHasO1bGKN9V35jFmpKqjPJeEwUkFXlFjNbYDFw1/658j5/WWUQXGvb9e4rpPT4mU="

cache:
  directories:
    - $HOME/.local/bin
    - $HOME/.stack

before_install:
  - |
    if ! test -f "$HOME/.local/bin/stack"
    then
      VERSION=2.3.0.1
      URL="https://github.com/commercialhaskell/stack/releases/download/v$VERSION/stack-$VERSION-linux-x86_64-static.tar.gz"
      curl --location --output stack.tar.gz "$URL"
      gunzip stack.tar.gz
      tar --extract --file stack.tar --strip-components 1
      mkdir --parents "$HOME/.local/bin"
      mv stack "$HOME/.local/bin"
      rm stack.tar
    fi
  - stack --version

install:
  - stack setup
  - stack build --only-dependencies --test

script:
  - stack build --no-run-tests --pedantic --test
  - stack build --test
  - stack sdist

deploy:
  provider: script
  on:
    tags: true
  skip_cleanup: true
  script: yes | stack upload .
